default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: your_username
  password: your_password
  host: localhost

development:
  <<: *default
  database: smileminder_development
  username: your_username
  password: your_password
  host: localhost

test:
  <<: *default
  database: your_app_test

production:
  <<: *default
  database: your_app_production
  username: <%= ENV['PRODUCTION_DB_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
  host: <%= ENV['PRODUCTION_DB_HOST'] %>
